name: union_player_app
description: A Union Player Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.1
  audio_service:
  audio_session:
  cloud_firestore:
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable:
  firebase_analytics: 8.1.2
  firebase_core: 1.3.0
  firebase_crashlytics: 2.0.6
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  flutter_svg: ^0.22.0
  form_field_validator: ^1.1.0
  intl:
  just_audio:
  koin_bloc:
  koin_flutter: ^0.11.0-nullsafety.0
  logger:
  marquee:
  path_provider:
  rxdart:
  shared_preferences:
  url_launcher: ^6.0.3
  uuid:
  webview_flutter:
  xml:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/localizations/en.json
    - assets/localizations/ru.json
    - assets/localizations/be.json
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/union_radio_logo_1.png"
  image_path_android: "assets/images/union_radio_logo_1.png"