name: union_player_app
description: A Union Player Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+36

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  app_tracking_transparency: ^2.0.4
  audio_service: ^0.18.11
  audio_session: ^0.1.16
  cloud_firestore: ^4.9.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.1.5+2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_core_web: ^2.7.0
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  get: ^4.6.6
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  intl: ^0.18.1
  just_audio: ^0.9.34
  just_audio_web: ^0.4.8
  logger: ^2.0.2
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.1
  simple_animations: ^5.0.2
  url_launcher: ^6.1.14
  uuid: ^3.0.7
  webview_flutter: ^4.2.4
  xml: ^6.3.0

dev_dependencies:
  flutter_launcher_icons:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/localizations/en.json
    - assets/localizations/ru.json
    - assets/localizations/be.json
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/union_radio_logo_1.png"
  image_path_android: "assets/images/union_radio_logo_1.png"