name: union_player_app
description: A Union Player Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.1.6+50

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_tracking_transparency: ^2.0.5
  audio_service: ^0.18.13
  audio_session: ^0.1.19
  cloud_firestore: ^4.17.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_analytics: ^10.10.4
  firebase_app_check: ^0.2.2+4
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_core_web: ^2.16.0
  firebase_crashlytics: ^3.5.4
  firebase_performance: ^0.9.4+4
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  get: ^4.6.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  just_audio: ^0.9.37
  just_audio_web: ^0.4.9
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  simple_animations: ^5.0.2
  tuple: ^2.0.2
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  webview_flutter: ^4.7.0
  xml: ^6.5.0

dev_dependencies:
  flutter_launcher_icons:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/localizations/en.json
    - assets/localizations/ru.json
    - assets/localizations/be.json
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/union_radio_logo_1.png"
  image_path_android: "assets/images/union_radio_logo_1.png"