name: union_player_app
description: A Union Player Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audio_session:
  cupertino_icons: ^1.0.2
  equatable:
  firebase_core:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3
  flutter_bloc:
  just_audio:
  koin_bloc:
  koin_flutter: ^0.11.0-nullsafety.0
  logger:
  flutter_screenutil: ^5.0.0
  form_field_validator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  webview_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/localizations/en.json
    - assets/localizations/ru.json
    - assets/about_us_page/test_page.html

  uses-material-design: true

