name: union_player_app
description: A Union Player Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.4+21

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.1
  audio_service: ^0.18.4
  audio_session: ^0.1.7
  cloud_firestore: ^3.4.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_analytics: ^9.1.12
  firebase_app_check: ^0.0.6+20
  firebase_auth: ^3.6.4
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  firebase_performance: ^0.8.2+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  flutter_svg: ^1.1.1
  form_field_validator: ^1.1.0
  get: ^4.6.5
  intl: ^0.17.0
  just_audio: ^0.9.22
  koin_flutter: ^0.11.0-nullsafety.0
  logger: ^1.1.0
  package_info_plus: ^1.4.3
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  simple_animations: ^5.0.0+2
  url_launcher: ^6.0.3
  uuid: ^3.0.6
  webview_flutter: ^3.0.4
  xml: ^6.1.0

dev_dependencies:
  flutter_launcher_icons:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/localizations/en.json
    - assets/localizations/ru.json
    - assets/localizations/be.json
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/union_radio_logo_1.png"
  image_path_android: "assets/images/union_radio_logo_1.png"